version: '3.2'

services:

  # Launch PostgreSQL Database.
  postgresDB:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - somenetwork
    environment:
      TZ: "Europe/Madrid"
      POSTGRES_USER: "developer"
      POSTGRES_PASSWORD: "strong_password"
      POSTGRES_DB: "quarkus-user-service-db-prod"


  # Launch User Service.
  userService:
    image: quarkus/quarkus-user-service
    restart: always
    ports:
      - "8080:8080"
    networks:
      - somenetwork
    environment:
      TZ: "Europe/Madrid"
    depends_on:
      - postgresDB


networks:
  somenetwork:
    driver: bridge
